# Generated by Django 4.1.3 on 2022-11-30 18:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('post_title', models.CharField(default='', max_length=1000)),
                ('post_content', models.TextField(default='', max_length=5000)),
                ('post_img', models.ImageField(default='', upload_to='Images')),
                ('post_date', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('comment_content', models.TextField(default='', max_length=5000)),
                ('timestamp', models.DateField(default=datetime.datetime.now)),
                ('comment_parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.comment')),
                ('comment_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.post')),
                ('comment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
